apiVersion: v1
kind: Namespace
metadata:
  name: kubelab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: kubelab
spec:
  replicas: 2
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          resources:
            requests: { cpu: 20m, memory: 32Mi }
            limits: { cpu: 100m, memory: 64Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: kubelab
spec:
  selector: { app: web }
  ports:
    - port: 80
      targetPort: 80
